In [44]:

import numpy as np
import matplotlib.pyplot as plt
%matplotlib qt

from sympy.solvers import solve
from sympy import Symbol
import math
import random
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter

In [45]:
np.random.normal(0, 1)

-0.4093838667400573

In [133]:
def function(x,C_0,delta,slope):    
    
    # x = J, C, F
    
    dot_J = -delta*(x[0]**3 +slope*(x[1]-C_0)*x[0] + x[2])
    #dot_C = -(x[1]+4*x[0])
    dot_C = 10*(-1*x[0]-1*x[1])
    dot_F = -1*(x[1])
    #dot_F =0
    
    return([dot_J, dot_C, dot_F])
   

In [134]:
def sys(iv, dt, time,function,C_0,delta,slope):
    n = int(time/dt)
    t = np.linspace(0,time,n)
    x = np.array([[ i for i in iv]]*n)
    n_ord = len(iv)
    
    a = iv
    
    for i in range(1,n):
        X = function(a,C_0,delta,slope)
        X[2] = X[2] + 0*np.random.normal(0,1000)
        a = a + np.array(X)*dt
        x[i] = a
    return np.array(x)


In [135]:
time = 100
dt = 0.001

C_0 = 0
slope = 1
delta = 100

x= sys([0.5,-1.5,-1.5], dt,time,function,C_0,delta,slope)

n = int(time/dt)
t = np.linspace(0,time,n)

In [136]:
fig = plt.figure(figsize=(5,5))
fig.subplots_adjust(wspace = 0.5, hspace = 0.3)
ax1 = fig.add_subplot(3,1,1)
ax2 = fig.add_subplot(3,1,2)
ax3 = fig.add_subplot(3,1,3)

T1 = 25000
T2 = 320000

T1 = 0
T2 = 1000000

ax1.plot(t[T1:T2],x[:,0][T1:T2], '-',label ='J')
#ax1.plot(t,x[:,0], 'r--',label ='smJ')

ax2.plot(t[T1:T2],x[:,1][T1:T2], '-',label ='T')
ax2.plot(t[T1:T2],-x[:,0][T1:T2], 'm--',label ='smC')

ax3.plot(t[T1:T2],x[:,2][T1:T2], '-',label ='F')
ax3.plot(t,-x[:,0], 'g--',label ='smF',alpha=0.5)

#ax3.plot(t,-(x[:,0]**3 +slope*(x[:,1]-C_0)*x[:,0] + x[:,2]))
#ax2.legend(loc=1)

ax1.set_ylabel(r'$J$',rotation=0)

ax2.set_ylabel(r'$T$',rotation=0)
ax3.set_ylabel(r'$F$',rotation=0)
ax3.set_xlabel(r'$t$')


ax1.grid(alpha=0.5)
ax2.grid(alpha=0.5)
ax3.grid(alpha=0.5)
plt.show()


In [137]:
#3D PLOT

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
T1 = 10000
T2 = 100000
m=25

ax.plot(x[:,1][T1:T2], x[:,2][T1:T2],x[:,0][T1:T2],".",markersize=0.7,alpha=0.8)

ax.set_xlabel('T')
ax.set_ylabel('F')
ax.set_zlabel('J')

plt.show()

### Slow manifold

In [65]:
from mpl_toolkits.mplot3d import axes3d
import matplotlib.pyplot as plt
import numpy as np

def plot_implicit(fn, bbox=(-0.5,0.5)):
    ''' create a plot of an implicit function
    fn  ...implicit function (plot where fn==0)
    bbox ..the x,y,and z limits of plotted interval'''
    xmin, xmax, ymin, ymax, zmin, zmax = bbox*3
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    A = np.linspace(xmin, xmax, 100) # resolution of the contour
    B = np.linspace(xmin, xmax, 100) # number of slices
    A1,A2 = np.meshgrid(A,A) # grid on which the contour is plotted

    for z in B: # plot contours in the XY plane
        X,Y = A1,A2
        Z = fn(X,Y,z)
        #cset = ax.contour(X, Y, Z+z, [z], zdir='z',)
        # [z] defines the only level to plot for this contour for this value of z

    for y in B: # plot contours in the XZ plane
        X,Z = A1,A2
        Y = fn(X,y,Z)
        cset = ax.contour(X, Y+y, Z, [y], zdir='y',alpha = 0.4)

    for x in B: # plot contours in the YZ plane
        Y,Z = A1,A2
        X = fn(x,Y,Z)
        #cset = ax.contour(X+x, Y, Z, [x], zdir='x')

    # must set plot limits because the contour will likely extend
    # way beyond the displayed level.  Otherwise matplotlib extends the plot limits
    # to encompass all values in the contour.
    ax.set_zlim3d(-5,5)
    ax.set_xlim3d(xmin,xmax)
    ax.set_ylim3d(ymin,ymax)
    ax.set_xlabel('T')
    ax.set_ylabel('F')
    ax.set_zlabel('J')
    plt.show()

In [66]:
def goursat_tangle(x,y,z):
    C_0 = 0
    slope = 1
    return(z**3+z*slope*(x-C_0)+y)

plot_implicit(goursat_tangle)

/home/lcbob/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:25: UserWarning: No contour levels were found within the data range.


In [67]:
T1 = 80000
T2 = 1000000
m=25

plt.plot(x[:,1][T1:T2], x[:,2][T1:T2],x[:,0][T1:T2],".",markersize=0.7,alpha=1)



ax.set_zlim3d([np.min(x[:,0][T1:T2]),np.max(x[:,0][T1:T2])])

plt.show()

In [68]:
np.max(x[:,0][T1:T2])

0.44483610806691326

In [69]:
len(x)

100000

In [138]:
from numpy import linalg as LA


In [139]:
def eigenvalue_fast(value):

    #parameter
    C_0 = 0
    slope = 1
    delta = 100

    #value
    J,C,F = value
    
    Mat = np.zeros((3,3))

    Mat[0,0] = -delta*(3*J**2+slope*(C-C_0))
    Mat[0,1] = -delta*slope*J
    Mat[0,2] = -delta


    Mat[1,0] = -10
    Mat[1,1] = -10
    Mat[1,2] = 0
    
    Mat[2,0] = 0
    Mat[2,1] = -1
    Mat[2,2] = 0

    eigva, v = LA.eig(Mat)
    
    return(eigva,v)

In [140]:
list_values = np.array([eigenvalue_fast(value)[0] for value in x])

In [141]:
fig = plt.figure(figsize=(8,8))
T1 = 0
T2 = 100000

for i in range(5):
    print(i)
    fig.subplots_adjust(wspace = 0.5, hspace = 0.3)
    ax1 = fig.add_subplot(3,1,1)
    ax2 = fig.add_subplot(3,1,2)
    ax3 = fig.add_subplot(3,1,3)
    
    ax1.plot(t[T1:T2],x[:,0][T1:T2], 'g.-',label ='s',markersize=0.1)
        
    ax2.plot(t[T1:T2],list_values[:,i][T1:T2].real,'.-',markersize=2,alpha=0.5)
    ax2.plot(t[T1:T2],0+0*list_values[:,i][T1:T2].real,'k--',alpha=0.5)
    #ax2.plot(t[T1:T2],-1+0*list_values[:,i][T1:T2].real,'k--',alpha=0.5)
    #ax2.plot(t[T1:T2],np.absolute(list_values[:,i][T1:T2]),'-',alpha=0.5)
    
    ax3.plot(t[T1:T2],0*list_values[:,i][T1:T2].real,'k--',alpha=0.5)
    ax3.plot(t[T1:T2],list_values[:,i][T1:T2].imag,'.',markersize=0.7)

         
         
plt.show()

0
1
2
3


/home/lcbob/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  
/home/lcbob/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  if __name__ == '__main__':
/home/lcbob/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous ax

IndexError: index 3 is out of bounds for axis 1 with size 3

array([-52.05905564, -15.27217584,  -1.25777454])

In [150]:
w,v = eigenvalue_fast(x[29815])
for i in range(len(w)):
    vect = v[:,i]
    vect = vect/np.linalg.norm(vect)
    print(w[i],'\n',vect)

-104.82359925693305 
 [-0.99448466 -0.10487734 -0.00100051]
-16.413753841073184 
 [-0.53916623 -0.84064067 -0.05121563]
-0.5812099175508032 
 [-0.42779885  0.45419724  0.7814685 ]


In [ ]:
eigenvalue_fast(x[62000])

In [19]:
len(x)

100000

In [31]:
eigenvalue_fast(x[57000])

(array([-9.863441  +0.j        ,  0.02775481+0.31719736j,
         0.02775481-0.31719736j]),
 array([[-0.99463412+0.j        , -0.08922418+0.07669031j,
         -0.08922418-0.07669031j],
        [-0.10292753+0.j        , -0.02626285-0.30014648j,
         -0.02626285+0.30014648j],
        [-0.01043526+0.j        ,  0.94624521+0.j        ,
          0.94624521-0.j        ]]))

In [28]:
eigenvalue_fast(x[57500])

(array([-6.35230193+0.j        ,  0.08631412+0.38726363j,
         0.08631412-0.38726363j]),
 array([[-0.9867317 +0.j        ,  0.11463632-0.13206621j,
          0.11463632+0.13206621j],
        [-0.16038415+0.j        ,  0.07899345+0.35441814j,
          0.07899345-0.35441814j],
        [-0.02524819+0.j        , -0.91518569+0.j        ,
         -0.91518569-0.j        ]]))

In [29]:
eigenvalue_fast(x[58000])

(array([-1.33265352,  1.22154363,  0.61429045]),
 array([[-0.67139996,  0.73993064,  0.39208851],
        [-0.59276729, -0.52051208, -0.4815094 ],
        [-0.44480225,  0.4261101 ,  0.78384647]]))

In [30]:
eigenvalue_fast(x[58500])

(array([-23.67001034+0.j        ,  -0.16759999+0.11898653j,
         -0.16759999-0.11898653j]),
 array([[-0.99909192+0.j        ,  0.01918102+0.01575271j,
          0.01918102-0.01575271j],
        [-0.04256887+0.j        , -0.16411744+0.11651412j,
         -0.16411744-0.11651412j],
        [-0.00179843+0.j        , -0.97922105+0.j        ,
         -0.97922105-0.j        ]]))

In [22]:
eigenvalue_fast(x[30400])

(array([-24.59643264+0.j        ,  -0.1624335 +0.11946405j,
         -0.1624335 -0.11946405j]),
 array([[-0.9991596 +0.j        ,  0.01996566+0.01461835j,
          0.01996566-0.01461835j],
        [-0.04095515+0.j        , -0.15918016+0.11707134j,
         -0.15918016-0.11707134j],
        [-0.00166509+0.j        , -0.97997125+0.j        ,
         -0.97997125-0.j        ]]))